import React from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Input, Row, Col, Button } from "antd";
import Layout from "../../components/Layout";
import Items from "../../api/items.json";

const Index = () => {
  const router = useRouter();
  const query = router.query;
  const id = query.id;
  console.log("console log nya query", query);
  return (
    <div
      style={{
        backgroundImage: 'url("/totoro025.jpeg")',
      }}
      className="bg-no-repeat bg-cover bg-center"
    >
      <Head>
        <title>Linkies</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/http.png" />
      </Head>

      <Layout search={false}>
        <div className="flex flex-col justify-center items-center h-96 gap-5 font-semibold">
          <div
            className="bg-[#FA5D32] rounded-full w-full px-5 py-3 text-center text-white"
            onClick={() => router.push(`${Items?.items?.[id]?.shopee}`)}
          >
            Shopee
          </div>
          <div
            className="bg-[#4EAC44] rounded-full w-full px-5 py-3 text-center text-white"
            onClick={() => router.push(`${Items?.items?.[id]?.tokped}`)}
          >
            Tokopedia
          </div>
        </div>
        <center>
          <div
            className="bg-[#162E2D] rounded-full w-1/2 px-5 py-3 text-center text-white"
            onClick={() => router.push(`/`)}
          >
            Back
          </div>
        </center>
        {/* {items?.map((e, index) => {
          return (
            <Col xs={24} sm={24} md={8} lg={8}>
              <div
                className="mb-5 py-2 px-5 drop-shadow-lg rounded-full opacity-80"
                style={{ backgroundColor: "#A0BF78" }}
                onClick={() => router.push(`/product/${index}`)}
              >
                <p
                  className="opacity-100 font-bold text-center"
                  style={{
                    color: "#193E34",
                    textOverflow: "ellipsis",
                    whiteSpace: "nowrap",
                    overflow: "hidden",
                  }}
                >
                  {e?.name}
                </p>
              </div>
            </Col>
          );
        })} */}
      </Layout>
    </div>
  );
};

export default Index;
