import { useState } from "react";
import { Input, Row, Col, Button } from "antd";
import Head from "next/head";
import { useRouter } from "next/router";
import Items from "../api/items.json";

export default function Home() {
  const [items, setItems] = useState(Items?.items);
  const router = useRouter();

  return (
    <div
      style={{
        backgroundImage: 'url("/totoro025.jpeg")',
      }}
      className="bg-no-repeat bg-cover bg-center"
    >
      <Head>
        <title>Linkies</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/http.png" />
      </Head>

      <div className="flex flex-col h-screen pt-10 px-4 items-center">
        <Row>
          <p className="font-bold text-white text-3xl drop-shadow-lg">
            ✨ &nbsp; Linkies &nbsp; ✨
          </p>
        </Row>
        <Row className="w-full drop-shadow-lg mt-5">
          <Col xs={18} sm={18} md={20} lg={20}>
            <Input
              // placeholder="Find items.."s
              className="w-full pl-5 rounded-l-full border-r-0 font-semibold"
              style={{
                backgroundColor: "#E3D27C",
                borderColor: "#E3D27C",
                color: "#193E34",
              }}
              onChange={(e) => {
                let a;

                if (e?.target?.value === "") {
                  a = Items?.items;
                } else {
                  a = items?.filter((x) =>
                    x?.name?.toLowerCase()?.includes(e?.target?.value)
                  );
                }
                setItems(a);
              }}
            />
          </Col>
          <Col xs={6} sm={6} md={4} lg={4}>
            <Button
              className="w-full rounded-r-full border-l-0 font-semibold text-right pr-10"
              style={{
                backgroundColor: "#E3D27C",
                borderColor: "#E3D27C",
                color: "#193E34",
              }}
            >
              Search
            </Button>
          </Col>
        </Row>
        <Row
          className="mt-5 w-full overflow-scroll hiddenScrollbar"
          gutter={10}
        >
          {items?.map((e) => {
            return (
              <Col xs={24} sm={24} md={8} lg={8}>
                <div
                  className="mb-5 py-2 px-5 drop-shadow-lg rounded-full opacity-80"
                  style={{ backgroundColor: "#A0BF78" }}
                  onClick={() => router.push(`${e?.link}`)}
                >
                  <p
                    className="opacity-100 font-bold text-center"
                    style={{
                      color: "#193E34",
                      textOverflow: "ellipsis",
                      whiteSpace: "nowrap",
                      overflow: "hidden",
                    }}
                  >
                    {e?.name}
                  </p>
                </div>
              </Col>
            );
          })}
        </Row>
      </div>
    </div>
  );
}
