import { useState } from "react";
import { Input, Row, Col, Button } from "antd";
import Head from "next/head";
import { useRouter } from "next/router";
import Items from "../api/items.json";
import Layout from "../components/Layout";

export default function Home() {
  const [items, setItems] = useState(Items?.items);
  const router = useRouter();

  return (
    <div
      style={{
        backgroundImage: 'url("/totoro025.jpeg")',
      }}
      className="bg-no-repeat bg-cover bg-center"
    >
      <Head>
        <title>Linkies</title>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        ></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/http.png" />
      </Head>

      <Layout>
        <Row gutter={10}>
          {items?.map((e) => {
            return (
              <Col xs={24} sm={24} md={8} lg={8}>
                <div
                  className="mb-5 py-2 px-5 drop-shadow-lg rounded-full opacity-80"
                  style={{ backgroundColor: "#A0BF78" }}
                  onClick={() => router.push(`${e?.link}`)}
                >
                  <p
                    className="opacity-100 font-bold text-center"
                    style={{
                      color: "#193E34",
                      textOverflow: "ellipsis",
                      whiteSpace: "nowrap",
                      overflow: "hidden",
                    }}
                  >
                    {e?.name}
                  </p>
                </div>
              </Col>
            );
          })}
        </Row>
      </Layout>
    </div>
  );
}
